version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py
    volumes:
      - ./uploads:/app/uploads
    networks:
      - document-processor-network

  frontend:
    build:
      context: ./document-processor_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - document-processor-network

networks:
  document-processor-network:
    driver: bridge